services:

  db:
    image: ankane/pgvector
    container_name: text2sql-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: text2sqldb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./dvdrental.tar:/docker-entrypoint-initdb.d/dvdrental.tar

  web:
    image: python:3.11-slim
    container_name: text2sql-web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./:/app
    command: /bin/bash -c "python /app/init/init_table_docs.py && streamlit run main.py --server.port=8501 --server.address=0.0.0.0"

    depends_on:
      - db